update workflow

diff --git a/.github/workflows/example.yml b/.github/workflows/example.yml
--- a/.github/workflows/example.yml
+++ b/.github/workflows/example.yml
@@ -39,7 +39,28 @@ jobs:
         uses: ./ #devjoes/kustomize-action@v0.0.2
         with:
           kustomize-path: ./example/input/dev
-          output-actions: '[{"type":"LoggerOutputAction","logErrors":true,"logYaml":false},{"type":"VariableOutputAction","outputVariableName":"yaml","errorsVariableName":"errors"},{"type":"FileOutputAction","createDirIfMissing":true,"fileOpenFlags":"w","dontOutputIfErrored":true,"fileName":"/tmp/${GITHUB_RUN_ID}_output"}]'
+          output-actions: '[{"type":"LoggerOutputAction","logErrors":true,"logYaml":false},{"type":"VariableOutputAction","outputVariableName":"yaml","errorsVariableName":"errors"},{"type":"FileOutputAction","createDirIfMissing":true,"fileOpenFlags":"w","dontOutputIfErrored":true,"fileName":"/tmp/${GITHUB_RUN_ID}_output.yaml"}]'
           extra-resources: './example/output/test.yaml,./example/output/core-infra.yaml'
           verbose: false
         continue-on-error: true
+      - name: Commit kustomize output
+        run: |
+            printenv
+            git config --global user.name "$GITHUB_WORKFLOW"
+            git config --global user.email "$GITHUB_WORKFLOW@github.com"
+            git fetch origin $GITHUB_BASE_REF
+            if [[ -n "$(git status --porcelain $GITHUB_BASE_REF -- ./example/output/dev.yaml)"; then
+              echo "Aborting - deployed YAML has changed. Please get latest changes from ${GITHUB_BASE_REF}."
+              exit 1
+            fi
+            mv /tmp/${GITHUB_RUN_ID}_output.yaml ./example/output/dev.yaml
+            if [[ -z "$(git status --porcelain $GITHUB_BASE_REF -- ./example/output/dev.yaml)"; then
+              echo "No changes to commit."
+              exit 0
+            fi
+            git add ./example/output/dev.yaml
+            git commit -m "Updated deployed YAML from $GITHUB_WORKFLOW"
+            git push origin HEAD:$GITHUB_HEAD_REF
+
+
+
